<?php
/**
 * @file
 * Provide an fractionslider display style.
 *
 * This is a placeholder file so drupal will enable the module. All logic is contained in
 * other files located with the module.
 */

/**
 * Implements hook_init().
 */
function fractionslider_init() {
  $path = libraries_get_path('fractionslider');
  drupal_add_js($path . '/jquery.fractionslider.js');
}

/**
 * Implements hook_preprocess_page().
 */
function fractionslider_preprocess_page(&$vars) {
}

/**
 * Implements hook_menu().
 */
function fractionslider_menu() {
  $items = array();

  $items['admin/config/user-interface/fractionslider'] = array(
    'title' => 'FractionSlider',
    'description' => 'Configuration for FractionSlider',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fractionslider_form'),
    'access arguments' => array('access fractionslider content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function fractionslider_permission() {
  return array(
    'access fractionslider content' => array(
      'title' => t('Access FractionSlider for Customize.'),
    ),
  );
}

/**
 * Configuration form.
 */
function fractionslider_form($form, &$form_state) {
$slider = '<div class="slider-wrapper">
  <div class="responisve-container">
    <div class="slider">
      <div class="fs_loader"></div>
      <div class="slide"> <img src="/sites/all/modules/views_fractionslider/images/01_box_top.png" width="361" height="354" data-position="-152,142" data-in="left" data-delay="200" data-out="right"> <img src="/sites/all/modules/views_fractionslider/images/01_box_bottom.png"  width="422" height="454"  data-position="138,-152" data-in="bottomRight" data-delay="200"> <img src="/sites/all/modules/views_fractionslider/images/01_waves.png"  width="1449" height="115" data-position="240,17" data-in="left" data-delay="" data-out="left"> <img src="/sites/all/modules/views_fractionslider/images/01_outofthebox.png"  data-position="20,330" data-in="bottomLeft" data-delay="500" data-out="fade" style="width:auto; height:auto">
        <p class="claim light-green" data-position="30,30" data-in="top" data-step="1" data-out="top">jQuery FractionSlider</p>
        <p class="teaser orange" data-position="90,30" data-in="left" data-step="2" data-delay="500">animate multiple elements</p>
        <p class="teaser green" data-position="90,30" data-in="left" data-step="2" data-special="cycle" data-delay="3000">full control over each element</p>
        <p class="teaser turky" data-position="90,30" data-in="left" data-step="2" data-special="cycle" data-delay="5500" data-out="none">opensource and free</p>
      </div>
      <div class="slide" data-in="slideLeft"> <img src="/sites/all/modules/views_fractionslider/images/02_big_boxes.png"  data-fixed data-position="25,445" data-in="fade" data-delay="0" data-out="right"> <img src="/sites/all/modules/views_fractionslider/images/02_small_boxes.png" data-position="80,220" data-in="fade" data-delay="500" data-out="bottomRight"> <img src="/sites/all/modules/views_fractionslider/images/01_box_bottom.png"  data-position="138,-152" data-in="bottomRight" data-delay="200" data-out="bottomRight">
        <p class="claim light-green small"  data-position="30,30" data-in="top" data-step="1" data-out="top">What to expect</p>
        <p class="teaser turky small" data-position="90,30" data-in="bottom" data-step="2" data-delay="500">unlimited elements</p>
        <p class="teaser turky small" data-position="120,30" data-in="bottom" data-step="2" data-delay="1500">many transitions</p>
        <p class="teaser turky small" data-position="150,30" data-in="bottom" data-step="2" data-delay="2500">unlimited slides</p>
        <p class="teaser turky small" data-position="180,30" data-in="bottom" data-step="2" data-delay="3500">background animation</p>
        <p class="teaser turky small" data-position="210,30" data-in="bottom" data-step="2" data-delay="4500">easy to use</p>
      </div>
    </div>
  </div>
</div>';

  $form['fractionslider_markup'] = array(
    '#title' => t('FractionSlider HTML'),
    '#type' => 'textarea',
    '#description' => t('This is what HTML structure for FractionSlider. Change elements/text under < div class="slide"> to see changes.'),
    '#default_value' => variable_get('fractionslider_markup', $slider),
  );
  
  $form['fractionslider_controls'] = array(
    '#type' => 'select',
    '#title' => t('Controls'),
    '#options' => array(
      'false' => t('False'),
      'true' => t('True'),
    ),
    '#default_value' => variable_get('fractionslider_controls', 'false'),
    '#description' => t('controls on/off'),
  );
  
  $form['fractionslider_pager'] = array(
    '#type' => 'select',
    '#title' => t('Pager'),
    '#options' => array(
      'false' => t('False'),
      'true' => t('True'),
    ),
    '#default_value' => variable_get('fractionslider_pager', 'false'),
    '#description' => t("pager inside of the slider on/off OR $('someselector') for a pager outside of the slider"),
  );

  return system_settings_form($form);
}

/**
 * Implements hook_block_info().
 */
function fractionslider_block_info() {

  $blocks['fractionslider'] = array(
    'info' => t('FractionSlider'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function fractionslider_block_view($delta = '') {
  $slider = drupal_get_form('fractionslider_form');
  $fraction = $slider['fractionslider_markup']['#value'];
  $control = $slider['fractionslider_controls']['#value'];
  $pager = $slider['fractionslider_pager']['#value'];

  drupal_add_js(array(
      'fractionslider' => array(
        'controls' => $control,
        'pager' => $pager
      )
    ), 'setting');

  switch ($delta) {
    case 'fractionslider':
      $block['title'] = 'FractionSlider';
      $block['content'] = $fraction;
      return $block;
  }
}

/**
 * Implements hook_form_alter().
 */
function fractionslider_form_alter($form, &$form_state, &$form_id) {
}
