<?php

function homepage_menu() {
  $items = array();

  //process page
  $items["homepage"] = array(
    'title' => "",
    'description' => "",
    'page callback' => 'homepage_page',
    'type' => MENU_CALLBACK,
    'access callback' => true
  );

  return $items;
}

function homepage_page() {

  drupal_add_css(drupal_get_path("module", "homepage") . '/homepage.css');
  drupal_add_js(drupal_get_path("module", "homepage") . '/homepage.js');

  $form = array();

  $form['social_nav'] = array(
    '#title' => "",
    '#markup' => ""
  );

  $form['header'] = array(
    'title' => "",
    'markup' => "<div class='header container-fluid'><div class='social_nav'></div><div class='bottom_line></div>'"
  );

  $form['main_navigation'] = array(
    '#markup' => "<div class='container'><div class='nav'>"
  );

  $form['slider'] = array(
    '#markup' => "<div class='slider'><h1>hello</h1></div>"
  );

  $form['latest_block'] = array(
    '#markup' => "<div class='latest'><h1>hello</h1></div>"
  );

  return $form;
}
